services:
  iomm:
    build:
      context: .
      dockerfile: Dockerfile
    image: iomm-toolbox:latest
    command: bash
    volumes:
      - .:/app:delegated
    networks:
      - app-network
    privileged: true
    tty: true
    stdin_open: true

networks:
  app-network:
    driver: bridge
